In [1]:
# import neccessary libraries 
import pandas as pd 
import numpy as np 
import io

In [2]:
#read an excel file located locally on your PC 
from google.colab import files 
uploaded = files.upload ()

Saving B Example 1 - Data Encoding.xlsx to B Example 1 - Data Encoding.xlsx

In [3]:
uploaded

{'B Example 1 - Data Encoding.xlsx': b'PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00A7\x82\xcfn\x01\x00\x00\x04\x05\x00\x00\x13\x00\x08\x02[Content_Types].xml \xa2\x04\x02(\xa0\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xacT\xc9n\xc20\x10\xbdW\xea?D\xbeV\x89\xa1\x87\xaa\xaa\x08\x1c\xba\x1c[$\xe8\x07\x98x\x92X$\xb6\xe5\x19(\xfc}\'fQU\xb1\x08\xc1%Ql\xcf[&\xf3<\x18\xad\xda&YB@\xe3l.\xfaYO$`\x0b\xa7\x8d\xadr\xf1=\xfdH\x9fE\x82\xa4\xacV\x8d\xb3\x90\x8b5\xa0\x18\r\xef\xef\x06\xd3\xb5\x07L\xb8\xdab.j"\xff"%\x165\xb4\n3\xe7\xc1\xf2N\xe9B\xab\x88?C%\xbd*\xe6\xaa\x02\xf9\xd8\xeb=\xc9\xc2Y\x02K)u\x18b8x\x83R-\x1aJ\xdeW\xbc\xbcQ23V$\xaf\x9bs\x1dU.\x94\xf7\x8d)\x14\xb1P\xb9\xb4\xfa\x1fI\xea\xca\xd2\x14\xa0]\xb1h\x19:C\x1f@i\xac\x01\xa8m2\x1f\x0c3\x86\t\x10\xb11\x14\xf2 g\x80\x06/#\xdd\xba\xca\xb82\n\xc3\xdax|`\xebG\x18\xba\x9d\xe3\xae\xb6u_\xfc;\x82\xd1\x90\x8cU\xa0O\xd5\xb2w\xb9j\xe4\x8f\x0b\xf3\x99s\xf3\xec4\xc8\xa5\xad\x89-\xcaZe\xecN\xf7\t\xfex\x18e|\xf5o,\xa4\xf3\x17\x81\xcf\xe8 \x9e1\x90\xf1y\xbd\x84\x08s\x86\x10i\xdd\x00\xde\xba\xed\x11\xf4\x1cs\xad\x02\xe8\t\xf1\xf4V7\x17\xf0\x17\xfb\x94\x0e\x8e\xd488\x8f\x9c\xda\x00\x97wa\x17\x91\xae:\xf5\x0c\x04\x81\x0c\xecCrh\xd8\xf6\x8c\x1c\xf9\xab\xdb\x0e\xdd\x9d\xa2A\x1f\xe0\x96\xf1\x0e\x1b\xfe\x02\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\xb5U0#\xf4\x00\x00\x00L\x02\x00\x00\x0b\x00\x08\x02_rels/.rels \xa2\x04\x02(\xa0\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xac\x92MO\xc30\x0c\x86\xefH\xfc\x87\xc8\xf7\xd5\xdd\x90\x10BKwAH\xbb!T~\x80I\xdc\x0f\xb5\x8d\xa3$\x1b\xdd\xbf\'\x1c\x10T\x1a\x83\x03G\x7f\xbd~\xfc\xca\xdb\xdd<\x8d\xea\xc8!\xf6\xe24\xac\x8b\x12\x14;#\xb6w\xad\x86\x97\xfaqu\x07*&r\x96Fq\xac\xe1\xc4\x11v\xd5\xf5\xd5\xf6\x99GJy(v\xbd\x8f*\xab\xb8\xa8\xa1K\xc9\xdf#F\xd3\xf1D\xb1\x10\xcf.W\x1a\t\x13\xa5\x1c\x86\x16=\x99\x81Z\xc6MY\xdeb\xf8\xae\x01\xd5BS\xed\xad\x86\xb0\xb77\xa0\xea\x93\xcf\x9b\x7f\xd7\x96\xa6\xe9\r?\x889L\xec\xd2\x99\x15\xc8sbg\xd9\xae|\xc8l!\xf5\xf9\x1aUSh9i\xb0b\x9er:"y_dl\xc0\xf3D\x9b\xbf\x13\xfd|-N\x9c\xc8R"4\x12\xf82\xcfG\xc7%\xa0\xf5\x7fZ\xb44\xf1\xcb\x9dy\xc47\t\xc3\xab\xc8\xf0\xc9\x82\x8b\x1f\xa8\xde\x01\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\xba\x00\xf8\x03P\x03\x00\x00J\x07\x00\x00\x0f\x00\x00\x00xl/workbook.xml\xacU]o\x9b0\x14}\x9f\xb4\xff`\xf9\x9db\x13 \t*\x9dB\xa0Z\xa4\xac\xab\xbav{\x894\xb9\xe0\x04\xab\x80\x99m\x9aT\xd5\xfe\xfb\xae\xa1\xb4\xeb\xba\x87\xee#"6\xf65\xc7\xe7^\x9f{}\xfc\xeePW\xe8\x96+-d\x13czD0\xe2M.\x0b\xd1\xecb|uy\xea\xcc0\xd2\x865\x05\xabd\xc3c|\xc75~w\xf2\xf6\xcd\xf1^\xaa\x9bk)o\x10\x004:\xc6\xa51m\xe4\xba:/y\xcd\xf4\x91ly\x03\x96\xadT530T;W\xb7\x8a\xb3B\x97\x9c\x9b\xbar=BB\xb7f\xa2\xc1\x03B\xa4^\x83!\xb7[\x91\xf3T\xe6]\xcd\x1b3\x80(^1\x03\xf4u)Z=\xa2\xd5\xf9k\xe0j\xa6n\xba\xd6\xc9e\xdd\x02\xc4\xb5\xa8\x84\xb9\xebA1\xaa\xf3h\xb5k\xa4b\xd7\x15\xb8}\xa0\x01:(xB\xf8S\x02\x8d7\xee\x04\xa6\x17[\xd5"WR\xcb\xad9\x02hw \xfd\xc2\x7fJ\\J\x9f\x85\xe0\xf02\x06\xafC\xf2]\xc5o\x85=\xc3GV*\xfcKV\xe1#V\xf8\x04F\xc9?\xa3Q\x90V\xaf\x95\x08\x82\xf7\x97h\xc1#7\x0f\x9f\x1coE\xc5?\x0f\xd2E\xacm\xcfXmO\xaa\xc2\xa8b\xdad\x850\xbc\x88\xf1\x14\x86r\xcf\x9fM\xa8\xaeM:Q\x81\xd5\xa3\x13o\x86\xdd\x93G9\x9f+T\xf0-\xeb*s\tB\x1e\xe1!3\xc2p\xee\x05v%\x08cQ\x19\xae\x1af\xf8R6\x06t\xf8\xe0\xd7\xbfj\xae\xc7^\x96\x12\x14\x8e.\xf8\xb7N(\x0e\x89\x05\xfa\x02_\xa1ey\xc4\xae\xf593%\xeaT\x15\xe3e\xb4\xb9\xd2\xe0\xfe\xe6\x0cT\x8a>\x95\xa0\xe5\xcd\x98\x19zC\xd1\xe5\xea\n\x9d~\\\xa7\xd9\xc5\xc6CK\xd9)\xcd5\xf2\x08\x9do\x12\xb1C)3\x0cA^\xa3E\xc3\xaa;#\xf2\xc1\x86\x1c\x94\xf9~\xe0\x93\x8c\x12\x8aN\x17\xeb\xf5f\x02dv@\xc5\xca\x0b\xcc\xe7\x8a\x17"7P \xd0{\xd9i\x0e\x13@Xo~\xca\x07\xf62\xf9\xfe #Xn\xc3\xecB\x9c\x87X\x0c\xef\xbf\xc6\x1cB\xa2\xa2Q\xf5\xe7F!x_\xa5k8\xf9O\xec\x16t\x00j+\x1e\xca\xc4\n\x0e\x9aN\xbe6\xb9\x8a\xe8\xd7\xfbt9#\xc9$!N@|\xcf\xf1C\xb2t\x16\xa73\xdf\t<2M\xe9\x84\xa6\xf3 \xfd\x0e\xce\xa80\xca%\xebL\xf9 1\x0b\x1dc\x9f\xfe\xc6\xf4\x81\x1dF\x0b%Q\'\x8a\'\x1a\xf7\xe4\xe1\xe7\xd8\xfe\x97f\xb4}\xb7\x0e\xdbb\xfaY\xf0\xbd~\x12\xa3\x1d\xa2\xc3\x17\xd1\x14r\x1fcg\x0e\xb5\xf8\xee\xd9h\xdf\x9b\xbe\x88\xc2\x94\xa0e2\x05\xa9\xa0a\xee=\x17\xbb\x12\xf8\x82\xbe\xa76\x8f\x95gy\xc5\xf8>\xa5\xfed\x1e$\xa9\x93$~\xe2\xf8\xcb`\xe1,(\r\x1c\x9a\xa6A0[L\xfd$\xc8z>\xeeO\x84\xfa\xa2\r\xc4\xfa\x1e5}\xa2e\x07V\xb7\x15G+\xb8 lM\xef\xa3\x8c\x91\x8a\xec6jU\xd0\xfe\x14\xc7/sV\xe5\x90[\xb6\xeb\x17\xce(\xf1\xe6v\x05?\x98\xb56}\x0f\xb2\x16\xc0\x90\xfad1%s\xdf!\xd9$p\xfc\xd9\xdcsf\xfe\xc4s\x96~\xeae\xc14K\xb3$\xb0\x07d\xef\x9d\xe8\x7fT\xdf>\xbb\xa2\xf1B\xb3,!\x97\xcc\xa5b\xf9\r\xa8\xfc\x82o\x13\xa6AQ\x83C\xc0\x17\x049\xb2v\xc7\xafN~\x00\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\x81>\x94\x97\xf3\x00\x00\x00\xba\x02\x00\x00\x1a\x00\x08\x01xl/_rels/workbook.xml.rels \xa2\x04\x01(\xa0\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xacRMK\xc40\x10\xbd\x0b\xfe\x870w\x9bv\x15\x11\xd9t/"\xecU\xeb\x0f\x08\xc9\xb4)\xdb&!3~\xf4\xdf\x1b*\xba]X\xd6K/\x03o\x86y\xef\xcd\xc7v\xf75\x0e\xe2\x03\x13\xf5\xc1+\xa8\x8a\x12\x04z\x13l\xef;\x05o\xcd\xf3\xcd\x03\x08b\xed\xad\x1e\x82G\x05\x13\x12\xec\xea\xeb\xab\xed\x0b\x0e\x9as\x13\xb9>\x92\xc8,\x9e\x148\xe6\xf8(%\x19\x87\xa3\xa6"D\xf4\xb9\xd2\x864j\xce0u2js\xd0\x1d\xcaMY\xde\xcb\xb4\xe4\x80\xfa\x84S\xec\xad\x82\xb4\xb7\xb7 \x9a)f\xe5\xff\xb9C\xdb\xf6\x06\x9f\x82y\x1f\xd1\xf3\x19\tI<\ry\x00\xd1\xe8\xd4!+\xf8\xc1E\xf6\x08\xf2\xbc\xfcfMy\xcek\xc1\xa3\xfa\x0c\xe5\x1c\xabK\x1e\xaa5=|\x86t \x87\xc8G\x1f\x7f)\x92s\xe5\xa2\x99\xbbU\xef\xe1tB\xfb\xca)\xbf\xdb\xf2,\xcb\xf4\xeff\xe4\xc9\xc7\xd5\xdf\x00\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\x03\xb5\x9d\xd3\r\x04\x00\x00\x02\x0e\x00\x00\x18\x00\x00\x00xl/worksheets/sheet1.xml\x9cW[o\xab8\x10~_i\xff\x03\xf2{\xb8\x87B\x14r\x14\x9aV\xdb\x87\x95V\xdb\xbd<;\xc4I\xac\x02f\x8d\x93\xb6{\xb4\xff}\xc76\x10b\x92(=Q/\x90\xf9\xfc\xcd|3c3\xcc\xbf}\x94\x85u$\xbc\xa1\xacJ\x91g\xbb\xc8"U\xce6\xb4\xda\xa5\xe8\xcf?\x9e\'1\xb2\x1a\x81\xab\r.XER\xf4I\x1a\xf4m\xf1\xf3O\xf3w\xc6\xdf\x9a=!\xc2\x02\x86\xaaI\xd1^\x88z\xe68M\xbe\'%nlV\x93\n,[\xc6K,\xe0\x96\xef\x9c\xa6\xe6\x04o\xd4\xa2\xb2p|\xd7\x8d\x9c\x12\xd3\ni\x86\x19\xbf\x87\x83m\xb74\'+\x96\x1fJR\tM\xc2I\x81\x05\xc4\xdf\xeci\xddtle~\x0f]\x89\xf9\xdb\xa1\x9e\xe4\xac\xac\x81bM\x0b*>\x15)\xb2\xca|\xf6\xb2\xab\x18\xc7\xeb\x02t\x7fx!\xce\xad\x0f\x0e?>\xfc\x06\x9d\x1b\xf5\xfd\xc8SIs\xce\x1a\xb6\x1560;:\xe6\xb1\xfc\xc4I\x1c\x9c\xf7Lc\xfdw\xd1x\xa1\xc3\xc9\x91\xca\x02\x9e\xa8\xfc\x1f\x0b\xc9\x9b\xf6\\\xfe\x89,\xf8A\xb2\xa8\'\x93\xe9\xe2\xb3\x03\xdd\xa4\xe8{\xe6\x85\xcb0v\x97\x93\xd8\r\xfcI\xe8E\xc1$^E\xd1\xc4[\x06q\x18\xfb\xeeS\x1c\xc4\xff\xa1\xc5|C\xa1\xc2R\x95\xc5\xc96EKo\xf6\xecy\xc8Y\xccU\x03\xfdE\xc9{3\xb8\xb6\x04^\xbf\x92\x82\xe4\x82\x80\x13\x0fY\xb2?\xd7\x8c\xbdI\xe0\x0b|\xe5\x02e\xa3\x00\x92\x12\xe7\x82\x1e\xc9#)\x8a\x14=\xfaS\xe8\xf1\x7f\x94\x17y\r.\x9c\xde\xc7\xf0\xba\xf3\xf7\xacz\xfa7nm\xc8\x16\x1f\n\xf1;{\xff\x85\xd0\xdd^\x80\xe3\xa9\x1d\x82V\xd9,\xb3\xcd\xe7\x8a49t)8\xb7C\xc5\x9b\xb3\x02H\xe0\xafUR\xb9\xdd\xa0\xcb\xf0\x87\x0e\x97n\xc4>E\x89\xedFQ\xe8F*$\xf1);\xcf\x97\x01\xf5K\xa0,j\t\xfc\x7f\xd7K\xbc\xc0N\xfc$\x8a\x1f\xa4\n\xbd\x04\xd2\x9d\x1f\x1a\xc1\xca\xbf[\xc8\x19\x05X\x15E\xd4S\\\xf3\xea\xe8xU2VX\xe0\xc5\x9c\xb3w\x0b\xfa\x14\x02oj,w\xbd7\x03\xb7\x97\xf5B\xd4\x12\xbb\x94\xe0\x14AZ \x11\rT\xe1\xb8p\xe7\xce\x11\x12\x9b\xb7\x88L#\x80\xa8Gx\xe7\x88\xc71\xc2?G\xac\xc6\x88\xe0\x1c\xf14F\x84=\xc2\x01a\xbd:\xc8\xed\xfd\xea$X&\xe4\x92.m\x83|\xf7\xba\xa6\x86.\x8d\xf0\xd5\xea\xe0\x14\x8eJ\xdcjh\xf4\xe0\xb84\xd2\xf64\xa6\x8f.\x0b\x82\x08\xee\x17$\xc1\x9d \xa3\x0c\x99\xb6\r\x05=\x18\x824\xa2\x15d\x18WCc\x98\x8c\x05\x8d\xe9\xe3\xcb\x82\xa0\x99\xee\x17$\xc1\x9d \xa3k2m\x1b\nJ\x0cA\x1a\xa1\x05\xf9F\x05VCc\x10\x8e\x05\x8d\xe9\xafTH\xee\xdd\xbb7\x94\x04w\x82\x8c&\xcf\xb4\xedV\x854B\x0b\x9a\x9e\xf2\xab[nh\x0c\xbd\xb1\xa01\xfd\x15Ap\xb8\xdc/H\x82;A\xc6&\xc8\xb4\xedV\x854B\x0b\n\xcd\n\x9d\x19\x03\xf8\xd8\xe6\xb10vp\xa5\xe9\x1e\xbe"I\x82;I\xc6\xa6\xcf\xb4\xed\xd6\xb1\xa0\x11\xad$c\xf9jh\xf4\xe3q\x8d\xc6\xf4W\x04\xc9\xd1\xee\xee\xa6\x93\xe0N\xd0\xa9\xe6\xaak2m\xbb\xd5t\x1a\xd1\x1e\x0b\x89\xfd\x90\x0c?\xe611\x04O/4\xe1\xd8\xdd\x95&L\xbe"P\x82;\x81FD\x99\xb6\xdd\xaa\x98F\xb4\xc7\x84\xb9\xab\x86\xc6\xf8\xc2\xb97\xa6\xbfR1\x0f\xc6\xf3/<x%\xba\x93d\xc4\x94)\xaa\x14\xdd\xdaX-\xa4=*\xcc\x9dun\r\xc6}x\xc1\xc3\x95:\xc1\\\xf7\x15Y\xfaA\xae\x1f\xb9\xc6q\x9d)\xaasY\xe63\xb7\x85\xb4\xbb\xcbl\xbe3kpI\x96v?L\x9cY-=>\xea\x89\xa9\xc6;\xf2+\xe6;Z5VA\xb6j\x18\x84\x1d\xca\xf5\xbc\xe8\xdap-X-GD9\xc0\xad\x99\x80\xb1\xad\xbb\xdb\xc3\xeb\x12\x81\x11\xca\xb5\xc1\xdb\x961\xd1\xdd\xc0D(y_\x898\xd4V\x8dk\xc2_\xe9\xbf0+B#1Na\xe4T\xefC)\xaa\x19\x17\x1cS\x01\xfefr\xf8\xe6/\x1b5B;\xfd\xdb\xdb\xe2\x7f\x00\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\xc1\x17\x10\xbeN\x07\x00\x00\xc6 \x00\x00\x13\x00\x00\x00xl/theme/theme1.xml\xecY\xcd\x8b\x1b7\x14\xbf\x17\xfa?\x0csw\xfc5\xe3\x8f%\xde\xe0\xcfl\x93\xdd$d\x9d\x94\x1c\xb5\xb6\xecQV32\x92\xbc\x1b\x13\x02%9\xf5R(\xa4\xa5\x97Bo=\x94\xd2@\x03\r\xbd\xf4\x8f\t$\xb4\xe9\x1f\xd1\'\xcd\xd8#\xad\xe5$\x9blJZv\r\x8bG\xfe\xbd\xa7\xa7\xf7\x9e~z\xf3t\xf1\xd2\xbd\x98zG\x98\x0b\xc2\x92\x96_\xbeP\xf2=\x9c\x8c\xd8\x98$\xd3\x96\x7fk8(4|OH\x94\x8c\x11e\tn\xf9\x0b,\xfcK\xdb\x9f~r\x11m\xc9\x08\xc7\xd8\x03\xf9Dl\xa1\x96\x1fI9\xdb*\x16\xc5\x08\x86\x91\xb8\xc0f8\x81\xdf&\x8c\xc7H\xc2#\x9f\x16\xc7\x1c\x1d\x83\xde\x98\x16+\xa5R\xad\x18#\x92\xf8^\x82bP{}2!#\xec\r\x95J\x7f{\xa9\xbcO\xe11\x91B\r\x8c(\xdfW\xaa\xb1%\xa1\xb1\xe3\xc3\xb2B\x88\x85\xe8R\xee\x1d!\xda\xf2a\x9e1;\x1e\xe2{\xd2\xf7(\x12\x12~h\xf9%\xfd\xe7\x17\xb7/\x16\xd1V&D\xe5\x06YCn\xa0\xff2\xb9L`|X\xd1s\xf2\xe9\xc1j\xd2 \x08\x83Z{\xa5_\x03\xa8\\\xc7\xf5\xeb\xfdZ\xbf\xb6\xd2\xa7\x01h4\x82\x95\xa6\xb6\xd8:\xeb\x95n\x90a\rP\xfa\xd5\xa1\xbbW\xefU\xcb\x16\xde\xd0_]\xb3\xb9\x1d\xaa\x8f\x85\xd7\xa0T\x7f\xb0\x86\x1f\x0c\xba\xe0E\x0b\xafA)>\\\xc3\x87\x9df\xa7g\xeb\xd7\xa0\x14_[\xc3\xd7K\xed^P\xb7\xf4kPDIr\xb8\x86.\x85\xb5jw\xb9\xda\x15d\xc2\xe8\x8e\x13\xde\x0c\x83A\xbd\x92)\xcfQ\x90\r\xab\xecRSLX"7\xe5Z\x8c\xee2>\x00\x80\x02R$I\xe2\xc9\xc5\x0cO\xd0\x08\xb2\xb8\x8b(9\xe0\xc4\xdb%\xd3\x08\x12o\x86\x12&`\xb8T)\rJU\xf8\xaf>\x81\xfe\xa6#\x8a\xb602\xa4\x95]`\x89X\x1bR\xf6xb\xc4\xc9L\xb6\xfc+\xa0\xd57 /\x9e={\xfe\xf0\xe9\xf3\x87\xbf=\x7f\xf4\xe8\xf9\xc3_\xb2\xb9\xb5*Kn\x07%SS\xee\xd5\x8f_\xff\xfd\xfd\x17\xde_\xbf\xfe\xf0\xea\xf17\xe9\xd4\'\xf1\xc2\xc4\xbf\xfc\xf9\xcb\x97\xbf\xff\xf1:\xf5\xb0\xe2\xdc\x15/\xbe}\xf2\xf2\xe9\x93\x17\xdf}\xf5\xe7O\x8f\x1d\xda\xdb\x1c\x1d\x98\xf0!\x89\xb1\xf0\xae\xe1c\xef&\x8ba\x81\x0e\xfb\xf1\x01?\x9d\xc40B\xc4\x92@\x11\xe8v\xa8\xee\xcb\xc8\x02^[ \xea\xc2u\xb0\xed\xc2\xdb\x1cX\xc6\x05\xbc<\xbfk\xd9\xba\x1f\xf1\xb9$\x8e\x99\xafF\xb1\x05\xdcc\x8cv\x18w:\xe0\xaa\x9a\xcb\xf0\xf0p\x9eL\xdd\x93\xf3\xb9\x89\xbb\x89\xd0\x91k\xee.J\xac\x00\xf7\xe73\xa0W\xe2R\xd9\x8d\xb0e\xe6\r\x8a\x12\x89\xa68\xc1\xd2S\xbf\xb1C\x8c\x1d\xab\xbbC\x88\xe5\xd7=2\xe2L\xb0\x89\xf4\xee\x10\xaf\x83\x88\xd3%Cr`%R.\xb4Cb\x88\xcb\xc2e \x84\xda\xf2\xcd\xdem\xaf\xc3\xa8k\xd5=|d#a[ \xea0~\x88\xa9\xe5\xc6\xcbh.Q\xecR9D15\x1d\xbe\x8bd\xe42r\x7f\xc1G&\xae/$Dz\x8a)\xf3\xfac,\x84K\xe6:\x87\xf5\x1aA\xbf\n\x0c\xe3\x0e\xfb\x1e]\xc46\x92Kr\xe8\xd2\xb9\x8b\x183\x91=v\xd8\x8dP<s\xdaL\x92\xc8\xc4~&\x0e!E\x91w\x83I\x17|\x8f\xd9;D=C\x1cP\xb21\xdc\xb7\t\xb6\xc2\xfdf"\xb8\x05\xe4j\x9a\x94\'\x88\xfae\xce\x1d\xb1\xbc\x8c\x99\xbd\x1f\x17t\x82\xb0\x8be\xda<\xb6\xd8\xb5\xcd\x893;:\xf3\xa9\x95\xda\xbb\x18St\x8c\xc6\x18{\xb7>sX\xd0a3\xcb\xe7\xb9\xd1W"`\x95\x1d\xecJ\xac+\xc8\xceU\xf5\x9c`\x01e\x92\xaak\xd6)r\x97\x08+e\xf7\xf1\x94m\xb0goq\x82x\x16(\x89\x11\xdf\xa4\xf9\x1aD\xddJ]8\xe5\x9cTz\x9d\x8e\x0eM\xe05\x02\xe5\x1f\xe4\x8b\xd3)\xd7\x05\xe80\x92\xbb\xbfI\xeb\x8d\x08Yg\x97z\x16\xee|]p+~o\xb3\xc7`_\xde=\xed\xbe\x04\x19|j\x19 \xf6\xb7\xf6\xcd\x10Qk\x82<a\x86\x08\n\x0c\x17\xdd\x82\x88\x15\xfe\\D\x9d\xabZl\xee\x94\x9b\xd8\x9b6\x0f\x03\x14FV\xbd\x13\x93\xe4\x8d\xc5\xcf\x89\xb2\'\xfcw\xca\x1ew\x01s\x06\x05\x8f[\xf1\xfb\x94:\x9b(e\xe7D\x81\xb3\t\xf7\x1f,kzh\x9e\xdc\xc0p\x92\xacs\xd6yUs^\xd5\xf8\xff\xfb\xaaf\xd3^>\xafe\xcek\x99\xf3Z\xc6\xf5\xf6\xf5Aj\x99\xbc|\x81\xca&\xef\xf2\xe8\x9eO\xbc\xb1\xe53!\x94\xee\xcb\x05\xc5\xbbBw}\x04\xbc\xd1\x8c\x070\xa8\xdbQ\xba\'\xb9j\x01\xce"\xf8\x9a5\x98,\xdc\x94#-\xe3q&?\'2\xda\x8f\xd0\x0cZCe\xdd\xc0\x9c\x8aL\xf5Tx3&\xa0c\xa4\x87u+\x15\x9f\xd0\xad\xfbN\xf3x\x8f\x8d\xd3Ng\xb9\xac\xba\x9a\xa9\x0b\x05\x92\xf9x)\\\x8dC\x97J\xa6\xe8Z=\xef\xde\xad\xd4\xeb~\xe8TwY\x97\x06(\xd9\xd3\x18aLf\x1bQu\x18Q_\x0eB\x14^g\x84^\xd9\x99X\xd1tX\xd1P\xea\x97\xa1ZFq\xe5\n0m\x15\x15x\xe5\xf6\xe0E\xbd\xe5\x87A\xdaA\x86f\x1c\x94\xe7c\x15\xa7\xb4\x99\xbc\x8c\xae\n\xce\x99Fz\x933\xa9\x99\x01Pb/3 \x8ftS\xd9\xbaqyjui\xaa\xbdE\xa4-#\x8ct\xb3\x8d0\xd20\x82\x17\xe1,;\xcd\x96\xfbY\xc6\xba\x99\x87\xd42O\xb9b\xb9\x1br3\xea\x8d\x0f\x11kE"\'\xb8\x81&&S\xd0\xc4;n\xf9\xb5j\x08\xb7*#4k\xf9\x13\xe8\x18\xc3\xd7x\x06\xb9#\xd4[\x17\xa2S\xb8v\x19I\x9en\xf8wa\x96\x19\x17\xb2\x87D\x94:\\\x93N\xca\x061\x91\x98{\x94\xc4-_-\x7f\x95\r4\xd1\x1c\xa2m+W\x80\x10>Z\xe3\x9a@+\x1f\x9bq\x10t;\xc8x2\xc1#i\x86\xdd\x18Q\x9eN\x1f\x81\xe1S\xaep\xfe\xaa\xc5\xdf\x1d\xac$\xd9\x1c\xc2\xbd\x1f\x8d\x8f\xbd\x03:\xe77\x11\xa4XX/+\x07\x8e\x89\x80\x8b\x83r\xea\xcd1\x81\x9b\xb0\x15\x91\xe5\xf9w\xe2`\xcah\xd7\xbc\x8a\xd29\x94\x8e#:\x8bPv\xa2\x98d\x9e\xc25\x89\xae\xcc\xd1O+\x1f\x18O\xd9\x9a\xc1\xa1\xeb.<\x98\xaa\x03\xf6\xbdO\xdd7\x1f\xd5\xcas\x06i\xe6g\xa6\xc5*\xea\xd4t\x93\xe9\x87;\xe4\r\xab\xf2C\xd4\xb2*\xa5n\xfdN-r\xaek.\xb9\x0e\x12\xd5yJ\xbc\xe1\xd4}\x8b\x03\xc10-\x9f\xcc2MY\xbcN\xc3\x8a\xb3\xb3Q\xdb\xb43,\x08\x0cO\xd46\xf8muF8=\xf1\xae\'?\xc8\x9d\xccZu@,\xebJ\x9d\xf8\xfa\xca\xdc\xbc\xd5f\x07w\x81<zp\x7f8\xa7R\xe8PBo\x97#(\xfa\xd2\x1b\xc8\x946`\x8b\xdc\x93Y\x8d\x08\xdf\xbc9\'-\xff~)l\x07\xddJ\xd8-\x94\x1aa\xbf\x10T\x83R\xa1\x11\xb6\xab\x85v\x18V\xcb\xfd\xb0\\\xeau*\x0f\xe0`\x91Q\\\x0e\xd3\xeb\xfa\x01\\a\xd0Evi\xaf\xc7\xd7.\xee\xe3\xe5-\xcd\x85\x11\x8b\x8bL_\xcc\x17\xb5\xe1\xfa\xe2\xbe\\\xd9|q\xef\x11 \x9d\xfb\xb5\xca\xa0Ymvj\x85f\xb5=(\x04\xbdN\xa3\xd0\xec\xd6:\x85^\xad[\xef\rz\xdd\xb0\xd1\x1c<\xf0\xbd#\r\x0e\xda\xd5nP\xeb7\n\xb5r\xb7[\x08j%e~\xa3Y\xa8\x07\x95J;\xa8\xb7\x1b\xfd\xa0\xfd +c`\xe5)}d\xbe\x00\xf7j\xbb\xb6\xff\x01\x00\x00\xff\xff\x03\x00PK\x03\x04\x14\x00\x06\x00\x08\x00\x00\x00!\x00\x8c\xe4\xdd\xf2)\x03\x00\x00\xbd\t\x00\x00\r\x00\x00\x00xl/styles.xml\xccV[o\xd30\x14~G\xe2?X~\xcfrYS\xda*\xc9\xb4\xae\x8b4iL\x88\x15\x89W7qZk\xbeD\x8e\xbb\xa5 \xfe;\xc7\xb9\xb4\x19\xbb\x00\x03\r^Z\xfb\xf8\xf8;\xdf\xb9\xf9$:\xa9\x05G\xb7TWL\xc9\x18\xfbG\x1eFTf*gr\x1d\xe3O\xcb\xd4\x99`T\x19"s\xc2\x95\xa41\xde\xd1\n\x9f$o\xdfD\x95\xd9qz\xbd\xa1\xd4 \x80\x90U\x8c7\xc6\x943\xd7\xad\xb2\r\x15\xa4:R%\x95pR(-\x88\x81\xad^\xbbU\xa9)\xc9+{Ip7\xf0\xbc\xb1+\x08\x93\xb8E\x98\x89\xecW@\x04\xd17\xdb\xd2\xc9\x94(\x89a+\xc6\x99\xd95X\x18\x89lv\xb1\x96J\x93\x15\x07\xaa\xb5?"\x19\xaa\xfd\xb1\x0eP\xad{#\x8d\xf4\x81\x1d\xc12\xad*U\x98#\xc0uUQ\xb0\x8c>\xa4;u\xa7.\xc9\x0eH\x80\xfc2$?t\xbd\xe0\x9e\xef\xb5~!\xd2\xc8\xd5\xf4\x96\xd9\xf4\xe1$*\x944\x15\xca\xd4V\x9a\x18\x1f\x03Q\x1b\x82\xd9\x8dTw2\xb5G\x90\xe1N+\x89\xaa/\xe8\x96p\x90\xf8\xd8M\xa2Lq\xa5\x9

In [4]:
df = pd.read_excel (io.BytesIO(uploaded['B Example 1 - Data Encoding.xlsx']))
df

   S.N  Country  Hours   Salary House
0    0   France   34.0  12000.0    No
1    1    Spain   37.0  49000.0   Yes
2    2  Germany   20.0  34000.0    No
3    3    Spain   58.0  41000.0    No
4    4  Germany   40.0  43333.3   Yes
5    5   France   45.0  28000.0   Yes
6    6    Spain   39.8  51000.0    No
7    7   France   28.0  89000.0   Yes
8    8  Germany   50.0  53000.0    No
9    9   France   47.0  33000.0   Yes

# **Reading a file in your google drive**

In [6]:
# import necessary libraries 
import io
import pandas as pd
from google.colab import drive

In [7]:
#To read/write data from Google Drive:
#Reference: 
# https://docs.google.com/spreadsheets/d/1BjJcin7bIqW1d-DKqUeHVWBNUPCzAq-b/edit?usp=sharing&ouid=100326668963958764285&rtpof=true&sd=true

drive.mount('/content/drive')

df = pd.read_excel('/content/drive/My Drive/Colab Notebooks/1_House_Sales_Data.xlsx')

Mounted at /content/drive

In [8]:
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357